import os
sid = os.environ.get("Twilio_api_id")
key = os.environ.get("Auth_token")
number = os.environ.get("Twilio_number")
my_number = os.environ.get("my_number")
Test_id = os.environ.get("Twilio_Test_api_id")
Test_key = os.environ.get("Auth_Test_Token")
secret_key = os.environ.get("Secret_key")

print(sid)
print(key)
print(number)
print(my_number)
print(Test_id)
print(Test_key)
print(secret_key)
